modelo.Usuario=repositoriosAdHoc.RepositorioUsuarioAdHocJPA
modelo.Producto=repositoriosAdHoc.RepositorioProductoAdHocJPA
modelo.Categoria=repositoriosAdHoc.RepositorioCategoriasAdHocJPA

repositoriosAdHoc.RepositorioProductoAdHoc=repositoriosAdHoc.RepositorioProductoAdHocJPA
repositoriosAdHoc.RepositorioUsuarioAdHoc=repositoriosAdHoc.RepositorioUsuarioAdHocJPA
repositoriosAdHoc.RepositorioCategoriasAdHoc=repositoriosAdHoc.RepositorioCategoriasAdHocJPA