usuarios.modelo.Usuario=usuarios.repositoriosAdHoc.RepositorioUsuarioAdHocJPA
modelo.Producto=repositoriosAdHoc.RepositorioProductoAdHocJPA
modelo.Categoria=repositoriosAdHoc.RepositorioCategoriasAdHocJPA

repositoriosAdHoc.RepositorioProductoAdHoc=repositoriosAdHoc.RepositorioProductoAdHocJPA
usuarios.repositoriosAdHoc.RepositorioUsuarioAdHoc=usuarios.repositoriosAdHoc.RepositorioUsuarioAdHocJPA
repositoriosAdHoc.RepositorioCategoriasAdHoc=repositoriosAdHoc.RepositorioCategoriasAdHocJPA