modelo.Usuario=repositorio.RepositorioUsuariosJPA
modelo.Categoria=repositorio.RepositorioCategoriasJPA
# A�ado estos servicios para inyecci�n de dependencias
usuarios.servicio.IServicioUsuario=usuarios.servicio.ServicioUsuario
servicio.IServiciosCategorias=servicio.ServicioCategorias
servicio.IServiciosProductos=servicio.ServicioProductos

usuarios.puertos.PublicadorEventos=usuarios.puertos.PublicadorEventosRabbitMQ
