spring.application.name=microservicio-compraventas

server.port=8082

spring.data.mongodb.uri=mongodb+srv://borjitasancho16_db_user:SanchoUMU2004@aadd.griu5rt.mongodb.net/compraventas?appName=AADD
spring.rabbitmq.url=amqps://oklxofze:TjosECA3Q1TT7Y4XbVEnj7XBnXym52qD@rat.rmq2.cloudamqp.com/oklxofze