# Puerto donde escuchar� la pasarela
server.port=8090
spring.application.name=pasarela

# �MUY IMPORTANTE! 
# Zuul por defecto bloquea cabeceras sensibles como "Authorization" y "Cookie".
# Dej�ndolo en blanco, permitimos que el token JWT viaje hacia los microservicios.
zuul.sensitiveHeaders=

# ----------------------------------------------------
# RUTAS DE LOS MICROSERVICIOS
# ----------------------------------------------------

# 1. Microservicio Usuarios (Puerto 8080)
zuul.routes.usuarios.path=/api/usuarios/**
zuul.routes.usuarios.url=http://localhost:8080/api/usuarios/

# 2. Microservicio Compraventas (Puerto 8082)
zuul.routes.compraventas.path=/api/compraventas/**
zuul.routes.compraventas.url=http://localhost:8082/compraventas/

# 3. Microservicio Productos (Puerto 8083)
zuul.routes.productos.path=/api/productos/**
zuul.routes.productos.url=http://localhost:8083/productos/
zuul.routes.productos.stripPrefix=true

#4. Credenciales para OAuth2 de Github
spring.security.oauth2.client.registration.github.client-id=Ov23lijKABMtM9XIlGWi
spring.security.oauth2.client.registration.github.client-secret=a1c1b8dc47534ef2af5d66cd833833ae97e6f3ef