spring.application.name=productos
server.port=8083

# Permitir sobrescritura de beans si hay conflictos internos
spring.main.allow-bean-definition-overriding=true

# ---------------------------------------------------------
# CONFIGURACION JPA / MySQL 
# ---------------------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/db_productos?createDatabaseIfNotExist=true&serverTimezone=CET
spring.datasource.username=root
spring.datasource.password=practicas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.rabbitmq.addresses=amqps://oklxofze:TjosECA3Q1TT7Y4XbVEnj7XBnXym52qD@rat.rmq2.cloudamqp.com/oklxofze

# Actualiza las tablas automaticamente si hay cambios en el modelo
spring.jpa.hibernate.ddl-auto=update

# Opcional: mostrar las consultas en consola (util para ver que hace)
spring.jpa.show-sql=true